In [6]:
import pandas as pd
from datetime import datetime

In [9]:
# Load event data
merged_event_jan = pd.read_csv('/Users/tianying/Documents/Statistics and Data Science/Course/Modern Data Analytics/MDA project/MDA-Georgia/Preprocessing/merged_event_jan.csv',delimiter=',')
merged_event_feb = pd.read_csv('/Users/tianying/Documents/Statistics and Data Science/Course/Modern Data Analytics/MDA project/MDA-Georgia/Preprocessing/merged_event_feb.csv',delimiter=',')
merged_event_mar = pd.read_csv('/Users/tianying/Documents/Statistics and Data Science/Course/Modern Data Analytics/MDA project/MDA-Georgia/Preprocessing/merged_event_mar.csv',delimiter=',')
merged_event_apr = pd.read_csv('/Users/tianying/Documents/Statistics and Data Science/Course/Modern Data Analytics/MDA project/MDA-Georgia/Preprocessing/merged_event_apr.csv',delimiter=',')

In [10]:
# Concatenate event data
dfs = [merged_event_jan,merged_event_feb,merged_event_mar,merged_event_apr]
combined_noise_event = pd.concat(dfs, ignore_index=True)

combined_noise_event.head()

,description,result_timestamp,noise_event_laeq_primary_detected_certainty,noise_event_laeq_primary_detected_class,certainty_percentage,month,day,hour,minute,second,milliseconds,lamax,laeq
0,MP 03: Naamsestraat 62 Taste,2022-01-01 00:01:31.362,NaN,NaN,NaN,1,1,0,1,31,362,70.4,68.8
1,MP 03: Naamsestraat 62 Taste,2022-01-01 00:02:19.368,NaN,NaN,NaN,1,1,0,2,19,368,NaN,NaN
2,MP 03: Naamsestraat 62 Taste,2022-01-01 00:02:23.368,NaN,NaN,NaN,1,1,0,2,23,368,NaN,NaN
3,MP 03: Naamsestraat 62 Taste,2022-01-01 00:02:33.370,NaN,NaN,NaN,1,1,0,2,33,370,93.4,87.4
4,MP 03: Naamsestraat 62 Taste,2022-01-01 00:02:57.373,NaN,NaN,NaN,1,1,0,2,57,373,94.3,87.0

In [ ]:
combined_noise_event.to_csv('combined_noise_event_Q1.csv', index=False)